"""empty message

Revision ID: df0075f691dc
Revises: 
Create Date: 2022-05-07 15:32:53.974553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0075f691dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('hobby',
    sa.Column('hid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hid'),
    sa.UniqueConstraint('group_id'),
    sa.UniqueConstraint('group_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('depart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['depart_id'], ['Department.did'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name', 'email', name='uix_user_name_email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index('ix_user_code', 'users', ['user_code', 'email'], unique=False)
    op.create_table('user2hobby',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.hid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hobby_id', name='uix_user_hobby')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user2hobby')
    op.drop_index('ix_user_code', table_name='users')
    op.drop_table('users')
    op.drop_table('hobby')
    op.drop_table('Department')
    # ### end Alembic commands ###
